name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Deploy-Vue
      uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
      with:
        username: 'AlexStek'
        reponame: 'vue2testtask'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged